### ISSUE TITLE
Better structure for settings

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#11]
Current Settings system has a big flaw, one setting exist in only one place and it is not reusable. Even minor change requires modifying multiple functions, for example, to change Font Style setting, you need to change ReaderSettingsBottomSheet's and ReaderSettings' corresponding setting. That may become a big scalability issue in the future, and, in fact, already is.

Instead of that, there is a scalable way, which puts every setting, subcategory and category in separate function. It may require more code to write to begin with, but it makes every setting, subcategory and category reusable.

This is approximate view of the new, scalable Settings system.
```
Category 1/
├── Subcategory 1/
│   ├── Setting 1
│   └── Setting 2
└── Subcategory 2/
    ├── Setting 3
    ├── Setting 4
    └── Setting 5
```
It's biggest advantage is reusability on every stage and it makes code look much cleaner.

### Task list

- [x] Create one root category, in which all category's subcategories are passed. - In individual settings' screen **components/** folder.
- [x] Create mutliple subcategories, in which all settings are passed. - In individual settings' screen **components/subcategories/** folder.
- [x] Create multiple settings. - In individual settings' screen **components/settings/** folder.
