### ISSUE TITLE
File tree in Browse

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#14]
The main problem of the current Browse screen is no filtering. All files are in the single space. While it may not be a problem if you have 10 files, what if you have 100? At first, Browse scanned only Downloads folder, which may be more convenient for some, may also be more inconvenient for others. That's why the solution should be flexible, letting users decide from where to add books themselves and keeping it from becoming a big mess.

#### So I propose a flexible solution: Switching between all/folders mode. 
 - **ALL** mode: Browse will act with the same pattern as now.
 - **FOLDERS** mode: Browse will structure itself as folders, remembering the last place you visited.

[**Suggestion needed**](https://github.com/Acclorite/book-story/labels/%F0%9F%93%9D%20Suggestion%20needed). Have an interesting idea on how to further improve this feature? Leave a comment with your idea below! Any ideas are welcome, even incorrect ones are still important, as they can give a birth to a correct one.

### Task list

- [ ] Sort, filter and mode(all/folders) options.
- [ ] Favorite folders. Pin, filter, sort.
- [ ] Grid/List layout with customization(e.g. grid size)
- [ ] When searching, enable ALL mode. (even if FOLDERS mode is selected)

**Comment by shuvashish76** [comment]
I'd suggest you to take a look how it's done in [Librera Reader](https://github.com/foobnix/LibreraReader) which is probably the best foss android reader after [KOReader](https://github.com/koreader/koreader).

**Comment by Acclorite** [comment]
> I'd suggest you to take a look how it's done in [Librera Reader](https://github.com/foobnix/LibreraReader) which is probably the best foss android reader after [KOReader](https://github.com/koreader/koreader).

Thank you for suggestion! Although it is kinda vague what exactly you mean. As for design, it will surely match Material3 theme.

**Comment by shuvashish76** [comment]
> Although it is kinda vague what exactly you mean.

Sorry for such lazy suggestion.

Here are my proposals.
- Option to add user specific multiple folders option from the settings only i.e. you can configure them from settings not browse.
- On browse add multiple horizontal tabs (for folders). Default one would be "All". Swipe left/right to switch tabs.
- Search/filter/sort would be specific to tabs/folder only.

**Comment by Acclorite** [comment]
> - Option to add user specific multiple folders option from the settings only i.e. you can configure them from settings not browse.

Don't really understand meaning of "multiple folders option", there will be options to sort, filter and add favorite folders.

> - On browse add multiple horizontal tabs (for folders). Default one would be "All". Swipe left/right to switch tabs.

If I understand the meaning of these tabs right, it's about specifying a pull of folders for specific tab, as a counterplay I have another suggestion - favorite folders, add a folder to favorite, then you may be able to force ignore order, bringing it to the top of the root directory(Internal Storage directory, the one with Android, Download, Documents folders etc).

> - Search/filter/sort would be specific to tabs/folder only.

Search will ignore folder structure and search through all files, as I feel that would speed up process if you need exact folder. As for per folder specific sort/filter it may make sense, but I also do not see why global sorting or filtering may not be enough for Browse.

To clarify - Browse is not the same screen as Librera has.

 If you think about Librera, it's like a castle.
While when you think about Browse screen, it's like a bridge to that castle. Itself, it does not do anything except adding books to the library, and I would like it to not loose that meaning.

Browse screen is a passage to "safe" territory, where your books are saved in app's internal storage, even if the file is lost you still able to change, read and do whatever you want to the book.

And in Librera it is more like core screen, which lets you read books straight up. 

I see it as favorite folders, which can be easily pinned, may be more than enough to satisfy all needs on Browse screen for user.


Thank you for detailed suggestion, I will think about it, maybe will find something satisfying both my and your vision.
If I understand something wrong, please correct me, as I didn't use Librera much. If you can counterargument, I would gladly continue ☺️

**Comment by shuvashish76** [comment]
> If you think about Librera, it's like a castle.
While when you think about Browse screen, it's like a bridge to that castle. Itself, it does not do anything except adding books to the library, and I would like it to not loose that meaning.

Got it 👍🏿
> If I understand the meaning of these tabs right, it's about specifying a pull of folders for specific tab

Yes something similar to https://github.com/libre-tube/LibreTube/pull/6026 design.
> Search will ignore folder structure and search through all files, as I feel that would speed up process if you need exact file.

My design suggestion was inspired from AppManager. (Download [AM](https://f-droid.org/packages/io.github.muntashirakon.AppManager/) > open any app i.e. [AppInfo](https://muntashirakon.github.io/AppManager/en/#sec:app-details-page) tab > swipe to change tabs, you can see there are search/filter specific to tab) Also take a look at their [Sort/Filter](https://muntashirakon.github.io/AppManager/en/#filter) option from the main page for some ideas.
But I get your point, if making it simple speeds up the result then I agree we don't need unnecessary complicated features for this.

Thanks for the detailed explanations. I can only think of designs as I'm not a dev. Hope you make the actual implementation better with user friendly design. 😇

**Comment by Acclorite** [comment]
> Thanks for the detailed explanations. I can only think of designs as I'm not a dev. Hope you make the actual implementation better with user friendly design. 😇

Thank you for suggestions too. Well, I would also appreciate design suggestions, anything that could improve the feature.

> But I get your point, if making it simple speeds up the result then I agree we don't need unnecessary complicated features for this.

What I fear is to make a feature overcomplicated. Sometimes it's better to have one good way than 10 bad ways. As for me, good example of perfect combination of functionality/simplicity is [Mihon](https://github.com/mihonapp/mihon). It is not overcomplicated, still very customizable. It has many features, but when you use it, you don't feel like you have a mess of hundreds of features you probably wouldn't ever use.

So my point is I want to give user freedom, but also point at the right direction, to not overcomplicate things. 

I'd say, user spends <10% of the time in Browse, so why would he create multiple tabs, if he could just pin folder with one click?

I like your suggestions, feel free to create Issues if something is missing / needs improvement.
