### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Thewisem** [Acclorite/book-story#4]
Fdroid is a free and open source app store which is loved by open source enthusiast. I believe this would be a great addition to the store

### Task list

- [x] Ensure that there are no Closed Source libraries.
- [x] Ensure that there are no unexpected network calls.
- [x] Ensure that the app works as expected.
- [x] Disable "Check for updates" setting by default. (or make prompt to user, asking to enable it)
- [x] Release new app version that is ready to be on FDroid.

**Comment by Acclorite** [comment]
I created merge request. You can track progress _[here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15486)_. I will close this issue after the app is added.

Sadly, there will be no [reproducible builds](https://f-droid.org/docs/Reproducible_Builds/), at least for now. As there is no backup option in the app right now, transferring may be problematic. Right now I plan Backup feature and will start implementing it soon, I will upload a new release after it is done, so going **GitHub version** → **Fdroid version** and vise-versa will be less troubling.

**Comment by Acclorite** [comment]
Book's Story was **successfully** merged in F-Droid.

And **with Reproducible Builds**, meaning the APK signature from F-Droid will be the same as from [Github Releases](https://github.com/Acclorite/book-story/releases), so the APK downloaded from Github is exact same from F-Droid. It may take up to a week for the app to appear in the store.

I will close this issue. After the app will appear in the store, I will update README with all links.
