### ISSUE TITLE
Improve EPUB parser.

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#42]
Most complaints were about the EPUB format. It currently uses outdated by ages parser, which as everyone can see cannot fulfill it's only usage - correctly parsing books. That is why the replacement is needed.

### Task list

- [ ] Replace current EPUB parser.
- [ ] More compatible, support as many books as it should.
- [ ] More correct parsing, preserve natural line breaks, aligned with actual book.
