### ISSUE TITLE
More book customization in BookInfo screen.

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#5]
Extending books customization will bring more freedom for users to edit the book for their liking.

### Task list

- [x] Edit Title.
- [x] Edit Cover Image.
- [x] Reset Cover Image.
- [x] Edit Description.
- [x] Edit Author.
- [x] Remove author & description update.
- [x] Change tips in Help screen (to match current behavior)
