### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#60]
Current UI may be fine, but part of it is outdated, another part is simply undeveloped. This should bring UI more fresh look. May change whole screens or just small UI components, making them look better. Does not cover new features, only improving look of the old ones. Tasks may vary and change.

[Suggestion needed](https://github.com/Acclorite/book-story/labels/%F0%9F%93%9D%20Suggestion%20needed). Have an interesting idea on how to further improve this feature? Leave a comment with your idea below! Any ideas are welcome, even incorrect ones are still important, as they can give a birth to a correct one.

### Task list

- [ ] Library
- [ ] History
- [ ] Browse
- [ ] Book Info
- [ ] About
- [ ] Settings
- [x] Help (7c92542, fcb33cc, 1b262e9)

**Comment by nNoidea** [comment]
- [ ] Allow for padding under the `bottom page indicator` 

or

- [ ] Allow the `bottom page indicator` to be at the top of the screen for better full gesture experience

## Why?
When trying to exit the app by swiping from bottom up, I sometimes accidentally touch the page indicator and switch my pages.

Here's what I mean by padding:
![asdasdasdasdasd](https://github.com/user-attachments/assets/fdd1eeef-f155-4971-b501-ffd122f1cf22)

Here's what I mean by page indicator at the top:
![top](https://github.com/user-attachments/assets/4cc8701d-b722-43b9-93ba-62d23a100af4)

**Comment by nNoidea** [comment]
- [ ] Add a optional toggle button for using the app (reading the books) *not* in fullscreen

## Why?
In some android distros they force you to swipe up twice to exit the app that's in fullscreen and again in some distros this feature cannot be disabled.

This sometimes causes me to swipe the page I am reading downwards with the first and I lose where I am, then I gotta swipe up again to exit the app.

Without full screen enabled, you can directly swipe up and it exists the app and the OS knows this gestures and does not swipe up what's on the screen.

It might be also useful for people that always want to be able to see their notifications and or time.

**Comment by Acclorite** [comment]
Fullscreen option is already implemented and is in Reader's Misc tab.

**Comment by Acclorite** [comment]
> Allow for padding under the bottom page indicator

@nNoidea, created an appropriate issue (#125).

**Comment by Acclorite** [comment]
Moving to the [milestone](https://github.com/Acclorite/book-story/milestone/4) and [discussion](https://github.com/Acclorite/book-story/discussions/126).
