### ISSUE TITLE
Show images in Reader

### ISSUE THREAD

**Issue by valentinfamery** [Acclorite/book-story#69]
**Why you want this feature to be implemented? Please describe.**
To be able to read all books with pictures

**Describe the feature you'd like to be implemented**
Display epub images in the correct place between text

### Task list
- [ ] Show images option
- [ ] Show titles(metadata) option
- [ ] Do not show images option

**Comment by Acclorite** [comment]
Maybe in the future. Currently not planning.
