### ISSUE TITLE
⚠️ Unexpected calls to googleapis.com

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#7]
<h3>Please read!</h3>

While testing my app with [Tracker Control](https://f-droid.org/en/packages/net.kollnig.missioncontrol.fdroid/) I ran into unexpected issue - some of the google libraries send network calls to various **googleapis.com** domains, such as **firebaselogging.googleapis.com**, **content-autofill.googleapis.com** and **android.googleapis.com**.

That is all my fault. By further investigating I discovered that it is caused by ML Kit from Google. I wasn't aware of that, but **it is** closed source. In the next release **all closed source** libraries will be removed from the app - along with **Built-in translator**. I understand that for someone it is a deal breaker.

Not so long ago I started preparing the app to be published on [Fdroid](https://f-droid.org/en/) #4, until then I need to fix all issues, and such unexpected things. Sorry for the trouble.

**Workaround for now(multiple methods):**

1. Block Internet access to the app. - The most reliable one.
2. Use [Tracker Control](https://f-droid.org/en/packages/net.kollnig.missioncontrol.fdroid/) to block any network calls from the app.
3. **Do not** use Built-in Translator.

Any advises are welcome, any critique is justified.
Sorry.

_Also note, if you do not care about Google (for example you use Google apps), then you don't have to worry about that for now. Workaround is for those who don't want to send Google any information (though I don't know what they send with these network calls)._

### Task list

- [x] Remove Built-In translator or replace ML Kit with Open source Library.
- [x] Remove all closed source libraries.
- [x] Prevent unnoticed closed source libraries (by highlighting them in Licenses screen).

**Comment by Acclorite** [comment]
After removing all Closed Source libraries and Built-in Translator (which is based on Closed Source libraries) there seems to be no more unexpected network calls. Please wait for the next release. Closing for now.
