### ISSUE TITLE
Replace licensed icons with free

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#9]
Replace all icons that require attribution with free, that do not. One good source with free icons is [Material Design Icons](https://fonts.google.com/icons) - licensed under Apache License 2.0. This will reduce amount of problems that can cause non-attributed icon. Also making them density-depended may increase performance.

### Task list

- [x] Replace "brand" app icon. (redraw)
- [x] Replace all icons with free ones.
- [x] Make all icons have SVG format.
- [x] Correct Credits for icons.
